// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://imfgwymvdncqrzvzztzy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltZmd3eW12ZG5jcXJ6dnp6dHp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4MzYyMjYsImV4cCI6MjA3NzQxMjIyNn0.zwSH6JlzRQ5oBK_fu7v_VKocjH9vAYWWSnJzgiQNfiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});